name: Ultimate RDP Gaming

on: workflow_dispatch

jobs:
  windows-rdp:
    runs-on: windows-latest
    timeout-minutes: 525600

    steps:
    - name: Setup Ngrok & Enable TS
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
        .\ngrok\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Set-Service TermService -StartupType Automatic
        Start-Service TermService
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "MaxConnectionTime" -Value 0
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "MaxDisconnectionTime" -Value 0
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "MaxIdleTime" -Value 0

    - name: Setup Gaming Environment
      run: |
        Invoke-WebRequest https://download.vb-audio.com/Download_CABLE/VBCABLE_Driver_Pack43.zip -OutFile vbaudio.zip
        Expand-Archive vbaudio.zip -DestinationPath C:\VBCABLE
        Start-Process -FilePath "C:\VBCABLE\VBCABLE_Setup_x64.exe" -ArgumentList '/install' -Wait
        Invoke-WebRequest https://github.com/ViGEm/ViGEmBus/releases/download/v1.21.442/ViGEmBus_1.21.442_x64_x86_arm64.exe -OutFile vigem.exe
        Start-Process -FilePath "vigem.exe" -ArgumentList '/quiet' -Wait

    - name: Enable RDP Access
      run: | 
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

  ubuntu-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
    - name: Install Terminal Services
      run: |
        sudo apt update
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo sed -i 's/max_bpp=32/max_bpp=128/g' /etc/xrdp/xrdp.ini
        sudo sed -i 's/xserverbpp=24/xserverbpp=128/g' /etc/xrdp/xrdp.ini
        sudo sed -i 's/crypt_level=high/crypt_level=none/g' /etc/xrdp/xrdp.ini
        sudo sed -i 's/security_layer=negotiate/security_layer=rdp/g' /etc/xrdp/xrdp.ini

    - name: Install Gaming Environment
      run: |
        sudo apt install -y ubuntu-desktop
        sudo apt install -y chromium-browser
        sudo apt install -y pulseaudio pavucontrol
        sudo apt install -y joystick jstest-gtk
        sudo adduser xrdp ssl-cert
        sudo sed -i 's/3389/53682/g' /etc/xrdp/xrdp.ini
        echo "load-module module-native-protocol-tcp auth-anonymous=1" | sudo tee -a /etc/pulse/default.pa
        sudo systemctl restart xrdp

    - name: Setup User
      run: |
        sudo useradd -m -s /bin/bash gaming
        sudo adduser gaming sudo
        echo "gaming:P@ssw0rd!" | sudo chpasswd
        echo "gaming ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/gaming

    - name: Setup Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
        unzip ngrok-v3-stable-linux-amd64.zip
        ./ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ./ngrok tcp 53682 &

    - name: Keep Alive
      run: |
        while true; do
          echo "🎮 Gaming System Active - $(date)"
          sleep 300
        done
